import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const chillax = localFont({
  src: [
    {
      path: "../public/font/Chillax-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/Chillax-Semibold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-chillax",
  display: "swap",
});

const supreme = localFont({
  src: [
    {
      path: "../public/font/Supreme-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/font/Supreme-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-supreme",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${chillax.variable} ${supreme.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
